version: '3.8'
services:
  httpd:
    container_name: httpd
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./
        target: /usr/local/apache2/htdocs/
